name: build-check

on:
  - push
  - pull_request
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build examples 
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: | 
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          fqbn: esp32:esp32:mh-et-live-esp32minikit
          sketch-paths: |
           - ./
          libraries: |
           - name: ArduinoOTA